#pragma once

#include <cstdint>
#include <WinUser.h>

/// Holds code related to user input from hardware devices.
/// This namespace is named more than just INPUT because INPUT is already defined by the
/// Windows API (https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-input).
namespace INPUT_CONTROL
{
    /// A key from a keyboard.
    /// A struct is used to contain a regular enum to have scoping along with
    /// implicit integer conversion (which wouldn't happen for an enum class).
    struct Key
    {
        /// Key codes.  Values come from the Windows API:
        /// https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
        enum Code : uint8_t
        {
            LEFT_MOUSE_BUTTON = VK_LBUTTON,
            RIGHT_MOUSE_BUTTON = VK_RBUTTON,
            CONTROL_BREAK_PROCESSING = VK_CANCEL,
            MIDDLE_MOUSE_BUTTON = VK_MBUTTON,
            X1_MOUSE_BUTTON = VK_XBUTTON1,
            X2_MOUSE_BUTTON = VK_XBUTTON2,
            BACKSPACE = VK_BACK,
            TAB = VK_TAB,
            CLEAR = VK_CLEAR,
            ENTER = VK_RETURN,
            SHIFT = VK_SHIFT,
            CTRL = VK_CONTROL,
            ALT = VK_MENU,
            PAUSE = VK_PAUSE,
            CAPS_LOCK = VK_CAPITAL,
            IME_KANA_MODE = VK_KANA,
            IME_HANGUEL_MODE = VK_HANGEUL,
            IME_HANGUL_MODE = VK_HANGUL,
            IME_JUNJA_MODE = VK_JUNJA,
            IME_FINAL_MODE = VK_FINAL,
            IME_HANJA_MODE = VK_HANJA,
            IME_KANJI_MODE = VK_KANJI,
            ESCAPE = VK_ESCAPE,
            IME_CONVERT = VK_CONVERT,
            IME_NONCONVERT = VK_NONCONVERT,
            IME_ACCEPT = VK_ACCEPT,
            IME_MODE_CHANGE_REQUEST = VK_MODECHANGE,
            SPACE = VK_SPACE,
            PAGE_UP = VK_PRIOR,
            PAGE_DOWN = VK_NEXT,
            END = VK_END,
            HOME = VK_HOME,
            LEFT_ARROW = VK_LEFT,
            UP_ARROW = VK_UP,
            RIGHT_ARROW = VK_RIGHT,
            DOWN_ARROW = VK_DOWN,
            SELECT = VK_SELECT,
            PRINT = VK_PRINT,
            EXECUTE = VK_EXECUTE,
            PRINT_SCREEN = VK_SNAPSHOT,
            INSERT = VK_INSERT,
            /// Had to had "_KEY" suffix added due to DELETE already defined by Windows API.
            DELETE_KEY = VK_DELETE,
            HELP = VK_HELP,
            ZERO = '0',
            ONE = '1',
            TWO = '2',
            THREE = '3',
            FOUR = '4',
            FIVE = '5',
            SIX = '6',
            SEVEN = '7',
            EIGHT = '8',
            NINE = '9',
            A = 'A',
            B = 'B',
            C = 'C',
            D = 'D',
            E = 'E',
            F = 'F',
            G = 'G',
            H = 'H',
            I = 'I',
            J = 'J',
            K = 'K',
            L = 'L',
            M = 'M',
            N = 'N',
            O = 'O',
            P = 'P',
            Q = 'Q',
            R = 'R',
            S = 'S',
            T = 'T',
            U = 'U',
            V = 'V',
            W = 'W',
            X = 'X',
            Y = 'Y',
            Z = 'Z',
            LEFT_WINDOWS = VK_LWIN,
            RIGHT_WINDOWS = VK_RWIN,
            APPLICATIONS = VK_APPS,
            SLEEP = VK_SLEEP,
            NUMPAD_0 = VK_NUMPAD0,
            NUMPAD_1 = VK_NUMPAD1,
            NUMPAD_2 = VK_NUMPAD2,
            NUMPAD_3 = VK_NUMPAD3,
            NUMPAD_4 = VK_NUMPAD4,
            NUMPAD_5 = VK_NUMPAD5,
            NUMPAD_6 = VK_NUMPAD6,
            NUMPAD_7 = VK_NUMPAD7,
            NUMPAD_8 = VK_NUMPAD8,
            NUMPAD_9 = VK_NUMPAD9,
            MULTIPLY = VK_MULTIPLY,
            ADD = VK_ADD,
            SEPARATOR = VK_SEPARATOR,
            SUBTRACT = VK_SUBTRACT,
            DECIMAL = VK_DECIMAL,
            DIVIDE = VK_DIVIDE,
            F1 = VK_F1,
            F2 = VK_F2,
            F3 = VK_F3,
            F4 = VK_F4,
            F5 = VK_F5,
            F6 = VK_F6,
            F7 = VK_F7,
            F8 = VK_F8,
            F9 = VK_F9,
            F10 = VK_F10,
            F11 = VK_F11,
            F12 = VK_F12,
            F13 = VK_F13,
            F14 = VK_F14,
            F15 = VK_F15,
            F16 = VK_F16,
            F17 = VK_F17,
            F18 = VK_F18,
            F19 = VK_F19,
            F20 = VK_F20,
            F21 = VK_F21,
            F22 = VK_F22,
            F23 = VK_F23,
            F24 = VK_F24,
            NAVIGATION_VIEW = VK_NAVIGATION_VIEW,
            NAVIGATION_MENU = VK_NAVIGATION_MENU,
            NAVIGATION_UP = VK_NAVIGATION_UP,
            NAVIGATION_DOWN = VK_NAVIGATION_DOWN,
            NAVIGATION_LEFT = VK_NAVIGATION_LEFT,
            NAVIGATION_RIGHT = VK_NAVIGATION_RIGHT,
            NAVIGATION_ACCEPT = VK_NAVIGATION_ACCEPT,
            NAVIGATION_CANCEL = VK_NAVIGATION_CANCEL,
            NUMLOCK = VK_NUMLOCK,
            SCROLL_LOCK = VK_SCROLL,
            OEM_NEC_PC_9800_NUM_EQUALS = VK_OEM_NEC_EQUAL,
            OEM_FUJITSU_OASYS_DICTIONARY = VK_OEM_FJ_JISHO,
            OEM_FUJITSU_OASYS_UNREGISTER_WORD = VK_OEM_FJ_MASSHOU,
            OEM_FUJITSU_OASYS_REGISTER_WORD = VK_OEM_FJ_TOUROKU,
            OEM_FUJITSU_OASYS_LEFT_OYAYUBI = VK_OEM_FJ_LOYA,
            OEM_FUJITSU_OASYS_RIGHT_OYAYUBI = VK_OEM_FJ_ROYA,
            LEFT_SHIFT = VK_LSHIFT,
            RIGHT_SHIFT = VK_RSHIFT,
            LEFT_CTRL = VK_LCONTROL,
            RIGHT_CTRL = VK_RCONTROL,
            LEFT_ALT = VK_LMENU,
            RIGHT_ALT = VK_RMENU,
            BROWSER_BACK = VK_BROWSER_BACK,
            BROWSER_FORWARD = VK_BROWSER_FORWARD,
            BROWSER_REFRESH = VK_BROWSER_REFRESH,
            BROWSER_STOP = VK_BROWSER_STOP,
            BROWSER_SEARCH = VK_BROWSER_SEARCH,
            BROWSER_FAVORITES = VK_BROWSER_FAVORITES,
            BROWSER_HOME = VK_BROWSER_HOME,
            VOLUME_MUTE = VK_VOLUME_MUTE,
            VOLUME_DOWN = VK_VOLUME_DOWN,
            VOLUME_UP = VK_VOLUME_UP,
            NEXT_TRACK = VK_MEDIA_NEXT_TRACK,
            PREVIOUS_TRACK = VK_MEDIA_PREV_TRACK,
            STOP_MEDIA = VK_MEDIA_STOP,
            PLAY_PAUSE_MEDIA = VK_MEDIA_PLAY_PAUSE,
            START_MAIL = VK_LAUNCH_MAIL,
            SELECT_MEDIA = VK_LAUNCH_MEDIA_SELECT,
            START_APPLICATION_1 = VK_LAUNCH_APP1,
            START_APPLICATION_2 = VK_LAUNCH_APP2,
            // ';:' key for US.
            OEM_1_SEMICOLON_COMMA_FOR_US = VK_OEM_1,
            OEM_PLUS = VK_OEM_PLUS,
            OEM_COMMA = VK_OEM_COMMA,
            OEM_MINUS = VK_OEM_MINUS,
            OEM_PERIOD = VK_OEM_PERIOD,
            /// '/?' key for US.
            OEM_2_FORWARD_SLASH_QUESTION_MARK_FOR_US = VK_OEM_2,
            /// '`~' key for US.
            OEM_3_BACKTICK_TILDE_FOR_US = VK_OEM_3,
            GAMEPAD_A = VK_GAMEPAD_A,
            GAMEPAD_B = VK_GAMEPAD_B,
            GAMEPAD_X = VK_GAMEPAD_X,
            GAMEPAD_Y = VK_GAMEPAD_Y,
            GAMEPAD_RIGHT_SHOULDER = VK_GAMEPAD_RIGHT_SHOULDER,
            GAMEPAD_LEFT_SHOULDER = VK_GAMEPAD_LEFT_SHOULDER,
            GAMEPAD_LEFT_TRIGGER = VK_GAMEPAD_LEFT_TRIGGER,
            GAMEPAD_RIGHT_TRIGGER = VK_GAMEPAD_RIGHT_TRIGGER,
            GAMEPAD_DPAD_UP = VK_GAMEPAD_DPAD_UP,
            GAMEPAD_DPAD_DOWN = VK_GAMEPAD_DPAD_DOWN,
            GAMEPAD_DPAD_LEFT = VK_GAMEPAD_DPAD_LEFT,
            GAMEPAD_DPAD_RIGHT = VK_GAMEPAD_DPAD_RIGHT,
            GAMEPAD_MENU = VK_GAMEPAD_MENU,
            GAMEPAD_VIEW = VK_GAMEPAD_VIEW,
            GAMEPAD_LEFT_THUMBSTICK_BUTTON = VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON,
            GAMEPAD_RIGHT_THUMBSTICK_BUTTON = VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON,
            GAMEPAD_LEFT_THUMBSTICK_UP = VK_GAMEPAD_LEFT_THUMBSTICK_UP,
            GAMEPAD_LEFT_THUMBSTICK_DOWN = VK_GAMEPAD_LEFT_THUMBSTICK_DOWN,
            GAMEPAD_LEFT_THUMBSTICK_RIGHT = VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT,
            GAMEPAD_LEFT_THUMBSTICK_LEFT = VK_GAMEPAD_LEFT_THUMBSTICK_LEFT,
            GAMEPAD_RIGHT_THUMBSTICK_UP = VK_GAMEPAD_RIGHT_THUMBSTICK_UP,
            GAMEPAD_RIGHT_THUMBSTICK_DOWN = VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN,
            GAMEPAD_RIGHT_THUMBSTICK_RIGHT = VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT,
            GAMEPAD_RIGHT_THUMBSTICK_LEFT = VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT,
            /// '[{' key for US.
            OEM_4_OPEN_SQUARE_BRACKET_CURLY_BRACE_FOR_US = VK_OEM_4,
            /// '\|' key for US.
            OEM_5_BACKSLASH_PIPE_FOR_US = VK_OEM_5,
            /// ']}' key for US.
            OEM_6_CLOSE_SQUARE_BRACKEY_CURLY_BRACE_FOR_US = VK_OEM_6,
            /// Single/double-quote key for US.
            OEM_7_SINGLE_DOUBLE_QUOTE_KEY_FOR_US = VK_OEM_7,
            OEM_8 = VK_OEM_8,
            JAPANESE_AX = VK_OEM_AX,
            RT_102_ANGLE_BRACKET_OR_BACKSLASH = VK_OEM_102,
            ICO_HELP = VK_ICO_HELP,
            ICO_00 = VK_ICO_00,
            IME_PROCEESS = VK_PROCESSKEY,
            ICO_CLEAR = VK_ICO_CLEAR,
            LOW_WORD_OF_VIRTUAL_KEY_FOR_NONKEYBOARD_FOR_UNICODE = VK_PACKET,
            OEM_NOKIA_ERICSSON_RESET = VK_OEM_RESET,
            OEM_NOKIA_ERICSSON_JUMP = VK_OEM_JUMP,
            OEM_NOKIA_ERICSSON_PA1 = VK_OEM_PA1,
            OEM_NOKIA_ERICSSON_PA2 = VK_OEM_PA2,
            OEM_NOKIA_ERICSSON_PA3 = VK_OEM_PA3,
            OEM_NOKIA_ERICSSON_WSCTRL = VK_OEM_WSCTRL,
            OEM_NOKIA_ERICSSON_CUSEL = VK_OEM_CUSEL,
            OEM_NOKIA_ERICSSON_ATTN = VK_OEM_ATTN,
            OEM_NOKIA_ERICSSON_FINISH = VK_OEM_FINISH,
            OEM_NOKIA_ERICSSON_COPY = VK_OEM_COPY,
            OEM_NOKIA_ERICSSON_AUTO = VK_OEM_AUTO,
            OEM_NOKIA_ERICSSON_ENLW = VK_OEM_ENLW,
            OEM_NOKIA_ERICSSON_BACKTAB = VK_OEM_BACKTAB,
            ATTN = VK_ATTN,
            CRSEL = VK_CRSEL,
            EXSEL = VK_EXSEL,
            ERASE_EOF = VK_EREOF,
            PLAY = VK_PLAY,
            ZOOM = VK_ZOOM,
            RESERVED_NO_NAME = VK_NONAME,
            PA1 = VK_PA1,
            OEM_CLEAR = VK_OEM_CLEAR
        };
    };
}
